api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import api

router = routers.DefaultRouter()
router.register('categories', api.CategoryViewSet, 'category')
router.register('subcategories', api.SubCategoryViewSet, 'subcategory'),
router.register('products', api.ProductViewSet, 'product')

urlpatterns = [
    path('', include(router.urls)),
]

authentication/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path, include
from . import views

app_name = "authentication"

urlpatterns = [
    # path("", include())
    path('login', views.login, name='login'),
    path('logout', views.signout, name='logout'),
    path('register', views.register, name='register'),
    path('getcookie', views.setCookie, name='getcookie'),
    path('savesession', views.save_session_data, name="save-session"),
    path('accesssession', views.access_session_data, name='access-session'),
    path('deletesession', views.delete_session_data, name='delete-session')
]

ecom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ecom"

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('cart', views.cart, name='cart'),
    path('category', views.category, name='category'),
    path('blog', views.blog, name='blog'),
    path('blog-detail', views.blogdetail, name='blog-detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('ecom.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

ecom/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    def __str__(self):
        return self.category_name


class SubCategory(models.Model):
    subcategory_name = models.CharField(max_length=50)
    category_name = models.ForeignKey(
        Category, on_delete=models.CASCADE, default="", blank=True)

    def __str__(self):
        return self.subcategory_name


class Product(models.Model):
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField(default=True)
    subcategory_name = models.ManyToManyField(SubCategory, blank=True)
    category_name = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return self.product_name

authentication/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth import logout


def login(request):
    if not request.session.get('session_status') == 'logged_in' and not request.session.get('user_id') == 1:
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)
                request.session['user_id'] = 1
                request.session['session_status'] = 'logged_in'
                return redirect('ecom:index')

            else:
                messages.info(request, 'Invalid Credentials')
                return redirect('authentication:login')
            # if request.session.has_key('is_logged'):
            #     return redirect(request, 'ecom:index')
        else:
            return render(request, 'authentication/login.html')
    else:
        return redirect('ecom:index')


def signout(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("authentication:login")


def register(request):
    if request.method == "POST":
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        username = request.POST["username"]
        passwd1 = request.POST["password"]
        passwd2 = request.POST["confirm_password"]
        email = request.POST["email"]
        if passwd1 == passwd2:
            user = User.objects.create_user(
                username=username, email=email, password=passwd1, first_name=first_name, last_name=last_name)
            user.save()
            print("User created...")
            return redirect("authentication:login")
        else:
            messages.error(
                request, "Passwords doesn't matched.")
            return render(request, "authentication/register.html")

    else:
        return render(request, "authentication/register.html")


def setCookie():
    if not request.COOKIES.get('team'):
        response = HttpResponse("Visiting for the first time.")
        response.set_cookie('team', 'barcelona', max_age=1200)
        return response
    else:
        return HttpResponse("Your favorite team is {}".format(request.COOKIES['team']))


def save_session_data(request):
    # set new data
    request.session['user_id'] = 20
    request.session['team'] = 'Barcelona'
    return HttpResponse("Session Data Saved")


def access_session_data(request):
    response = ""
    if request.session.get('user_id'):
        user_id = request.session.get('user_id')
        response += "User Id : {0} <br>".format(user_id)
    if request.session.get('team'):
        team = request.session.get('team')
        response += "Team : {0} <br>".format(team)

    if not response:
        return HttpResponse("No session data")
    else:
        return HttpResponse(response)


def delete_session_data(request):
    try:
        del request.session['user_id']
        del request.session['team']
    except KeyError:
        pass

    return HttpResponse("Session Data cleared")

ecom/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Category,SubCategory,Product


def index(request):
    title = 'Online Shopping India | Buy Mobile, Electronics, Fashion...'
    product_list = []
    products = Product.objects.all().values()
    for i in products:
        
        i.update({'discounted_price': i["product_price"]*(60/100)+i["product_price"]})
        product_list.append(i)
    return render(request, 'ecom/home.html', {'title': title, 'product_list': product_list})


def about(request):
    return render(request, 'ecom/about.html')


def cart(request):
    if request.session.get('session_status') == 'logged_in' and request.session.get('user_id') == 1:
        return render(request, 'ecom/cart.html')
    else:
        return redirect('authentication:login')


def category(request):
    return render(request, 'ecom/category.html')


def blog(request):
    return render(request, 'ecom/blog.html')


def blogdetail(request):
    return render(request, 'ecom/blogdetail.html')

templates/authentication/login.html
{%extends 'base.html'%}{%load static%}{% block title %}Glutter |
Login{%endblock%} {% block content %}

<!--================login_part Area =================-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6">
        <div class="login_part_text text-center">
          <div class="login_part_text_iner">
            <h2>New to our Shop?</h2>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a href="{% url 'authentication:register' %}" class="btn_3"
              >Create an Account</a
            >
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>
              Welcome Back ! <br />
              Please Sign in now
            </h3>
            <form
              class="row contact_form"
              action="{% url 'authentication:login' %}"
              method="post"
              novalidate="novalidate"
            >
              {% csrf_token %}
              <div class="col-md-12 form-group p_star">
                <input
                  type="text"
                  class="form-control"
                  id="username"
                  name="username"
                  value=""
                  placeholder="Username"
                />
              </div>
              <div class="col-md-12 form-group p_star">
                <input
                  type="password"
                  class="form-control"
                  id="password"
                  name="password"
                  value=""
                  placeholder="Password"
                />
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <input type="checkbox" id="f-option" name="selector" />
                  <label for="f-option">Remember me</label>

                  {% for message in messages %}
                  <h6>{{message}}</h6>
                  {% endfor %}
                </div>
                <button type="submit" value="submit" class="btn_3">
                  log in
                </button>
                <a class="lost_pass" href="#">forget password?</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================login_part end =================-->

{% endblock %}

templates/authentication/register.html
{%extends 'base.html'%}{%load static%}{% block title %}Glutter |
Register{%endblock%} {% block content %}

<!--================login_part Area =================-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6">
        <div class="login_part_text text-center">
          <div class="login_part_text_iner">
            <h2>Already have an account?</h2>
            <p>
              Login from here
              <a href="{% url 'authentication:login' %}" class="btn_3">Login</a>
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>
              Enter Registration Details
            </h3>
            <form
              class="row contact_form"
              action="{% url 'authentication:register' %}"
              method="post"
              novalidate="novalidate"
            >
              {% csrf_token %}
              <div class="col-md-12 form-group p_star">
                <input
                  type="text"
                  class="form-control"
                  id="first_name"
                  name="first_name"
                  value=""
                  placeholder="First Name"
                />
              <div class="col-md-12 form-group p_star">
                <input
                  type="text"
                  class="form-control"
                  id="last_name"
                  name="last_name"
                  value=""
                  placeholder="Last Name"
                />
              <div class="col-md-12 form-group p_star">
                <input
                  type="text"
                  class="form-control"
                  id="username"
                  name="username"
                  value=""
                  placeholder="Username"
                />
              </div>
              <div class="col-md-12 form-group p_star">
                <input
                  type="email"
                  class="form-control"
                  id="email"
                  name="email"
                  value=""
                  placeholder="email"
                />
              </div>
              <div class="col-md-12 form-group p_star">
                <input
                  type="password"
                  class="form-control"
                  id="password"
                  name="password"
                  value=""
                  placeholder="Password"
                />
              </div>
              <div class="col-md-12 form-group p_star">
                <input
                  type="password"
                  class="form-control"
                  id="confirm_password"
                  name="confirm_password"
                  value=""
                  placeholder="Confirm Password"
                />
              </div>
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <input type="checkbox" id="f-option" name="selector" />
                  <label for="f-option">Remember me</label>

                  {% for message in messages %}
                  <h6>{{message}}</h6>
                  {% endfor %}
                </div>
                <button type="submit" value="submit" class="btn_3">
                  Register
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================login_part end =================-->

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <!-- CSS here -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    
    <header>
        <!-- Header Start -->
       <div class="header-area">
            <div class="main-header ">
                
               <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-1 col-lg-1 col-md-1 col-sm-3">
                                <div class="logo">
                                  <a href="{% url 'ecom:index' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-8 col-md-7 col-sm-5">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav>                                                
                                        <ul id="navigation">                                                                                                                                     
                                            <li><a href="{% url 'ecom:index' %}">Home</a></li>
                                            <li><a href="{% url 'ecom:category' %}">Category</a></li>
                                            
                                            <li><a href="#">Blog</a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'ecom:blog' %}">Blog</a></li>
                                                    <li><a href="{% url 'ecom:blog-detail' %}">Blog Details</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Pages</a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'authentication:login' %}">Login</a></li>
                                                    <li><a href="{% url 'ecom:cart' %}">Cart</a></li>
                                                    <li><a href="checkout.html">Product Checkout</a></li>
                                                    <li><a href="{% url 'ecom:about' %}">About</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div> 
                            <div class="col-xl-5 col-lg-3 col-md-2 col-sm-2 fix-card">
                                <ul class="header-right f-right d-none d-lg-block d-flex justify-content-between">
                                    <li class="d-none d-xl-block">
                                        <div class="form-box f-right ">
                                            <input type="text" name="Search" placeholder="Search products">
                                            <div class="search-icon">
                                                <i class="fas fa-search special-tag"></i>
                                            </div>
                                        </div>
                                     </li>
                                    <li class=" d-none d-xl-block">
                                        <div class="favorit-items">
                                            <i class="far fa-heart"></i>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="shopping-card">
                                            <a href="{% url 'ecom:cart' %}"><i class="fas fa-shopping-cart"></i></a>
                                        </div>
                                    </li>
                                    {% if user.is_authenticated %}
                                    <li class="d-none d-lg-block"> <a href="{% url 'authentication:logout' %}" class="btn header-btn">Sign out</a></li>
                                    {% else %}
                                    <li class="d-none d-lg-block"> <a href="{% url 'authentication:login' %}" class="btn header-btn">Sign in</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
       </div>
        <!-- Header End -->
    </header>

    {% block content %}
    {% endblock %}

    <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-padding2">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-6">
                       <div class="single-footer-caption mb-50">
                         <div class="single-footer-caption mb-30">
                              <!-- logo -->
                             <div class="footer-logo">
                                 <a href="index.html"><img src="{% static 'img/logo/logo2_footer.png' %}" alt=""></a>
                             </div>
                             <div class="footer-tittle">
                                 <div class="footer-pera">
                                     <p>Glutter.in is selling all make in India Products.</p>
                                </div>
                             </div>
                         </div>
                       </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-3 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
                                    <li><a href="#">About</a></li>
                                    <li><a href="#"> Offers & Discounts</a></li>
                                    <li><a href="#"> Get Coupon</a></li>
                                    <li><a href="#">  Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>New Products</h4>
                                <ul>
                                    <li><a href="#">Woman Cloth</a></li>
                                    <li><a href="#">Fashion Accessories</a></li>
                                    <li><a href="#"> Man Accessories</a></li>
                                    <li><a href="#"> Rubber made Toys</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Support</h4>
                                <ul>
                                 <li><a href="#">Frequently Asked Questions</a></li>
                                 <li><a href="#">Terms & Conditions</a></li>
                                 <li><a href="#">Privacy Policy</a></li>
                                 <li><a href="#">Privacy Policy</a></li>
                                 <li><a href="#">Report a Payment Issue</a></li>
                             </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer bottom -->
                <div class="row">
                 <div class="col-xl-7 col-lg-7 col-md-7">
                     <div class="footer-copy-right">
                         <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | <a href="https://www.facebook.com/chetan.koranga" target="_blank">glutter corp.</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>                </div>
                 </div>
                  <div class="col-xl-5 col-lg-5 col-md-5">
                     <div class="footer-copy-right f-right">
                         <!-- social -->
                         <div class="footer-social">
                             <a href="https://twitter.com/ChetanKoranga"><i class="fab fa-twitter"></i></a>
                             <a href="https://www.facebook.com/chetan.koranga"><i class="fab fa-facebook-f"></i></a>
                             <a href="#"><i class="fab fa-behance"></i></a>
                             <a href="#"><i class="fas fa-globe"></i></a>
                         </div>
                     </div>
                 </div>
             </div>
            </div>
        </div>
    
        <!-- Footer End-->
    </footer>

<!-- JS here -->

    <!-- All JS Custom Plugins Link Here here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/animated.headline.js' %}"></script>
    
    <!-- Scrollup, nice-select, sticky -->
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

    <!-- contact js -->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
    
</html>

templates/ecom/about.html
{% extends 'base.html' %} {% load static %} {% block content %}


<!-- product list part start-->
<section class="about_us padding_top">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="about_us_content">
          <h5>Our Mission</h5>
          <h3>
            Donec imperdiet congue orci consequat mattis. Donec rutrum porttitor
            sollicitudin. Pellentesque id dolor tempor sapien feugiat ultrices
            nec sed neque.
          </h3>
          <div class="about_us_video">
            <img
              src="{%static 'img/about_us_video.png'%}"
              alt="#"
              class="img-fluid"
            />
            <a
              class="about_video_icon popup-youtube"
              href="https://www.youtube.com/watch?v=DWHB6nTyKDI"
            ></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- product list part end-->

<!-- feature part here -->
<section class="feature_part section_padding">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-lg-6">
        <div class="feature_part_tittle">
          <h3>
            Credibly innovate granular internal or organic sources whereas
            standards.
          </h3>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="feature_part_content">
          <p>
            Seamlessly empower fully researched growth strategies and
            interoperable internal or “organic” sources. Credibly innovate
            granular internal or “organic” sources whereas high standards in
            web-readiness.
          </p>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-3 col-sm-6">
        <div class="single_feature_part">
          <img src="{%static 'img/icon/feature_icon_1.svg'%}" alt="#" />
          <h4>Credit Card Support</h4>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6">
        <div class="single_feature_part">
          <img src="{%static 'img/icon/feature_icon_2.svg'%}" alt="#" />
          <h4>Online Order</h4>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6">
        <div class="single_feature_part">
          <img src="{%static 'img/icon/feature_icon_3.svg'%}" alt="#" />
          <h4>Free Delivery</h4>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6">
        <div class="single_feature_part">
          <img src="{%static 'img/icon/feature_icon_4.svg'%}" alt="#" />
          <h4>Product with Gift</h4>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- feature part end -->

<!-- client review part here -->
<section class="client_review">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="client_review_slider owl-carousel">
          <div class="single_client_review">
            <div class="client_img">
              <img src="{%static 'img/client.png'%}" alt="#" />
            </div>
            <p>
              "Working in conjunction with humanitarian aid agencies, we have
              supported programmes to help alleviate human suffering.
            </p>
            <h5>- Micky Mouse</h5>
          </div>
          <div class="single_client_review">
            <div class="client_img">
              <img src="{%static 'img/client_1.png'%}" alt="#" />
            </div>
            <p>
              "Working in conjunction with humanitarian aid agencies, we have
              supported programmes to help alleviate human suffering.
            </p>
            <h5>- Micky Mouse</h5>
          </div>
          <div class="single_client_review">
            <div class="client_img">
              <img src="{%static 'img/client_2.png'%}" alt="#" />
            </div>
            <p>
              "Working in conjunction with humanitarian aid agencies, we have
              supported programmes to help alleviate human suffering.
            </p>
            <h5>- Micky Mouse</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- client review part end -->

<!-- subscribe part here -->
<section class="subscribe_part section_padding">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="subscribe_part_content">
          <h2>Get promotions & updates!</h2>
          <p>
            Seamlessly empower fully researched growth strategies and
            interoperable internal or “organic” sources credibly innovate
            granular internal .
          </p>
          <div class="subscribe_form">
            <input type="email" placeholder="Enter your mail" />
            <a href="#" class="btn_1">Subscribe</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- subscribe part end -->

{% endblock %}